"""
Welele Story Forge™ — Collaborative Reasoning Data Models (Gate 2.1)
Enforces:
1. 4-Tier Fact Status (PROPOSED, INFERRED, CREATOR_CONFIRMED, CANONICAL)
2. Microscope Diagnostic Trace Structures
3. Semantic revisions and conversational director contracts.
"""

from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from datetime import datetime, timezone
from uuid import uuid4

from ..models.transition import StateMutation


class FactStatus(str, Enum):
    """
    4-Tier Fact Status Hierarchy:
    PROPOSED: Creative suggestions generated by the LLM (requires creator confirmation)
    INFERRED: Directly deduced from creator's explicit statements
    CREATOR_CONFIRMED: Inferences or proposals explicitly affirmed by the creator
    CANONICAL: Validated, invariant-checked, and committed into authoritative StoryState
    """
    PROPOSED = "PROPOSED"
    INFERRED = "INFERRED"
    CREATOR_CONFIRMED = "CREATOR_CONFIRMED"
    CANONICAL = "CANONICAL"


class ExtractedFact(BaseModel):
    """
    A single piece of narrative truth or proposal extracted from creator dialogue.
    """
    fact_id: str = Field(default_factory=lambda: f"fact_{uuid4().hex[:8]}")
    category: str = Field(
        ...,
        description="Category such as CHARACTER, MOTIVATION, SECRET, FLAW, RELATIONSHIP, KNOWLEDGE, EVENT, STAKES, OBSTACLE, PLANT"
    )
    target_entity: str = Field(..., description="Character name, relationship, or story element")
    statement: str = Field(..., description="The factual proposition in natural language")
    status: FactStatus = Field(default=FactStatus.INFERRED)
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    raw_evidence: Optional[str] = Field(default=None, description="Direct quote or snippet from creator response")


class RevisionRecord(BaseModel):
    """
    Captures when a creator revises or contradicts previously established story state,
    or makes a material story decision that alters narrative trajectory.
    """
    entity_or_topic: str
    previous_fact: str
    revised_fact: str
    revision_type: str = Field(
        default="FACTUAL_CONTRADICTION",
        description="'FACTUAL_CONTRADICTION' or 'MATERIAL_STORY_DECISION'"
    )
    material_consequences: List[str] = Field(
        default_factory=list,
        description="Immediate narrative ripples/consequences resulting from this revision/decision"
    )
    reconciliation_action: str = Field(
        default="REVISED_IN_STATE",
        description="How Forge reconciles the change (e.g., REVISED_IN_STATE, CONFLICT_FLAGGED)"
    )


class CollaborativeReasoningOutput(BaseModel):
    """
    Output produced by the Story Reasoning LLM (Conversational Director).
    """
    llm_understanding: str = Field(
        ...,
        description="Comprehensive narrative interpretation of what the creator said, subtext, and stakes"
    )
    extracted_facts: List[ExtractedFact] = Field(
        default_factory=list,
        description="All narrative facts extracted across characters, motives, knowledge, and beats"
    )
    proposed_mutations: List[StateMutation] = Field(
        default_factory=list,
        description="Concrete mutations mapped for Forge state validation and commitment"
    )
    revisions_detected: List[RevisionRecord] = Field(
        default_factory=list,
        description="Contradictions or intentional revisions to prior story state"
    )
    what_remains_unclear: str = Field(
        ...,
        description="Genuinely missing dramatic/story elements needed for narrative depth"
    )
    why_it_matters_to_the_story: str = Field(
        ...,
        description="The dramatic/screenwriting justification for the next conversational move"
    )
    conversational_action: str = Field(
        default="ASK_QUESTION",
        description="'ASK_QUESTION', 'CONCLUDE_STORY', or 'SYNTHESIZE_AND_CONTINUE'"
    )
    is_story_concluded: bool = Field(
        default=False,
        description="True if the creator has declared an ending boundary or completed the story"
    )
    next_conversational_move: Optional[str] = Field(
        default=None,
        description="Natural, evocative story question (ends with '?') when conversational_action is ASK_QUESTION; None or concluding synthesis when CONCLUDE_STORY"
    )


class ForgeReconciliationResult(BaseModel):
    """
    Result of Forge Kernel validating, constraining, and committing mutations into canonical state.
    """
    mutations_applied: List[StateMutation] = Field(default_factory=list)
    mutations_rejected: List[StateMutation] = Field(default_factory=list)
    reconciled_dependencies: List[str] = Field(default_factory=list)
    conflicts_flagged: List[str] = Field(default_factory=list)
    state_version_before: int = 1
    state_version_after: int = 1


class MicroscopeDiagnosticTrace(BaseModel):
    """
    The 8-Stage Diagnostic Microscope View for developers & testing.
    """
    trace_id: str = Field(default_factory=lambda: f"trace_{uuid4().hex[:8]}")
    cycle_index: int = 1
    creator_input: str
    llm_understanding: str
    facts_extracted: List[ExtractedFact]
    facts_proposed: List[StateMutation]
    forge_reconciliation: ForgeReconciliationResult
    canonical_state_summary: Dict[str, Any]
    what_remains_unclear: str
    why_it_matters_to_the_story: str
    next_conversational_move: Optional[str] = None
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    def format_microscope_view(self) -> str:
        """Renders the clean ASCII microscope trace for logging and verification."""
        sep = "=" * 70
        subsep = "-" * 70
        lines = [
            sep,
            f"  MICROSCOPE DIAGNOSTIC TRACE [Cycle #{self.cycle_index} | {self.trace_id}]",
            sep,
            "1. CREATOR INPUT:",
            f"   \"{self.creator_input}\"",
            subsep,
            "2. LLM UNDERSTANDING:",
            f"   {self.llm_understanding}",
            subsep,
            "3. FACTS EXTRACTED:",
        ]
        for idx, f in enumerate(self.facts_extracted, 1):
            lines.append(f"   [{idx}] [{f.status.value}] ({f.category}) {f.target_entity}: {f.statement}")
        lines.append(subsep)
        lines.append("4. FACTS PROPOSED (MUTATIONS):")
        for idx, m in enumerate(self.facts_proposed, 1):
            lines.append(f"   [{idx}] {m.mutation_type.value} {m.target_path} -> {m.rationale}")
        lines.append(subsep)
        lines.append("5. FORGE RECONCILIATION:")
        lines.append(f"   Applied Mutations: {len(self.forge_reconciliation.mutations_applied)}")
        lines.append(f"   Reconciled Dependencies: {self.forge_reconciliation.reconciled_dependencies}")
        if self.forge_reconciliation.conflicts_flagged:
            lines.append(f"   Conflicts / Revisions: {self.forge_reconciliation.conflicts_flagged}")
        lines.append(f"   State Version: {self.forge_reconciliation.state_version_before} -> {self.forge_reconciliation.state_version_after}")
        lines.append(subsep)
        lines.append("6. CANONICAL STATE SUMMARY:")
        for k, v in self.canonical_state_summary.items():
            lines.append(f"   {k}: {v}")
        lines.append(subsep)
        lines.append("7. WHAT REMAINS UNCLEAR:")
        lines.append(f"   {self.what_remains_unclear}")
        lines.append(subsep)
        lines.append("8. WHY IT MATTERS TO THE STORY:")
        lines.append(f"   {self.why_it_matters_to_the_story}")
        lines.append(subsep)
        lines.append("9. NEXT CONVERSATIONAL MOVE:")
        lines.append(f"   \"{self.next_conversational_move or 'None (Synthesized / Concluded)'}\"")
        lines.append(sep)
        return "\n".join(lines)
