import { Story } from '../types';

export const DEFAULT_STORIES: Story[] = [
  {
    id: 'story_blood_ties',
    title: 'Blood Ties',
    tagline: 'Two powerful families tied by blood, torn apart by greed.',
    synopsis: "When the matriarch of the mighty Khumalo dynasty collapses at the annual Sandton gala, a hidden will surfaces that names a secret daughter as the sole heir. Betrayal, boardroom warfare, and family secrets collide in Johannesburg's most dramatic showdown.",
    cover_image: '/banners/blood_ties_banner.jpg',
    vertical_poster: '/posters/blood_ties.jpg',
    genre: 'Drama • Family • Betrayal',
    language: 'isiZulu / English',
    available_languages: ['isiZulu', 'isiXhosa', 'English', 'Afrikaans', 'Sesotho'],
    tags: ['#BloodTies', '#MzansiDrama', '#BillionaireDynasty', '#Cliffhanger', '#WeleleOriginal'],
    creator_id: 'creator_zola',
    creator_name: 'Zola Dlamini',
    creator_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    is_verified_creator: true,
    rating: 4.98,
    total_episodes: 3,
    free_episodes_count: 2,
    coin_price_per_episode: 5,
    total_views: 3840000,
    total_likes: 512000,
    is_original: true,
    is_trending: true,
    status: 'published',
    episodes: [
      {
        id: 'ep_bt_1',
        series_id: 'story_blood_ties',
        episode_number: 1,
        title: 'The Golden Will',
        synopsis: 'The unsealed court document triggers panic in the boardroom.',
        duration_seconds: 68,
        video_url: '/videos/welele_placeholder.mp4',
        thumbnail_url: '/posters/blood_ties.jpg',
        is_free: true,
        coin_price: 0,
        cliffhanger_time: 58,
        cliffhanger_hook: 'Who authorized her DNA test before the funeral?',
        likes_count: 142000,
        views_count: 1240000,
        comments_count: 4820,
        published_at: '2026-08-20T12:00:00Z',
      },
      {
        id: 'ep_bt_2',
        series_id: 'story_blood_ties',
        episode_number: 2,
        title: 'Midnight at the Rank',
        synopsis: 'Sipho confronts the convoy blocking the workshop.',
        duration_seconds: 74,
        video_url: '/videos/welele_placeholder.mp4',
        thumbnail_url: '/posters/blood_ties.jpg',
        is_free: true,
        coin_price: 0,
        cliffhanger_time: 64,
        cliffhanger_hook: 'Will Bra Oupa draw his weapon first?',
        likes_count: 118000,
        views_count: 980000,
        comments_count: 3210,
        published_at: '2026-08-21T12:00:00Z',
      },
      {
        id: 'ep_bt_3',
        series_id: 'story_blood_ties',
        episode_number: 3,
        title: 'The Cartel Route',
        synopsis: 'The hidden ledger exposes illicit transit lines across Gauteng.',
        duration_seconds: 82,
        video_url: '/videos/welele_placeholder.mp4',
        thumbnail_url: '/posters/blood_ties.jpg',
        is_free: false,
        coin_price: 5,
        cliffhanger_time: 72,
        cliffhanger_hook: 'The security camera reveals the traitor in the family.',
        likes_count: 96000,
        views_count: 820000,
        comments_count: 2890,
        published_at: '2026-08-22T12:00:00Z',
      },
    ],
  },
  {
    id: 'story_queen_of_jozi',
    title: 'Queen of Jozi',
    tagline: "One woman's ruthless rise to the top of Johannesburg's underworld.",
    synopsis: "When her husband's gold syndication empire falls into rival hands, Nina Khumalo steps from the shadows to reclaim the throne in Sandton. Boardroom power plays meet street warfare in South Africa's most anticipated micro-drama.",
    cover_image: '/banners/queen_of_jozi_banner.jpg',
    vertical_poster: '/posters/queen_of_jozi.jpg',
    genre: 'Crime • Empire • Dynasty',
    language: 'isiZulu / English',
    available_languages: ['isiZulu', 'isiXhosa', 'English', 'Afrikaans', 'Sesotho'],
    tags: ['#QueenOfJozi', '#SandtonDynasty', '#MzansiCrime', '#WeleleSpotlight', '#Original'],
    creator_id: 'creator_zola',
    creator_name: 'Zola Dlamini',
    creator_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    is_verified_creator: true,
    rating: 4.99,
    total_episodes: 48,
    free_episodes_count: 3,
    coin_price_per_episode: 5,
    total_views: 5120000,
    total_likes: 740000,
    is_original: true,
    is_trending: true,
    status: 'published',
    episodes: [
      {
        id: 'ep_qj_1',
        series_id: 'story_queen_of_jozi',
        episode_number: 1,
        title: 'The Golden Takeover',
        synopsis: "Nina walks into the Sandton boardroom as the rival syndicate votes to liquidate her family's mining assets.",
        duration_seconds: 84,
        video_url: '/videos/welele_placeholder.mp4',
        thumbnail_url: '/posters/queen_of_jozi.jpg',
        is_free: true,
        coin_price: 0,
        cliffhanger_time: 74,
        cliffhanger_hook: 'Who signed over 51% of the shares before sunrise?',
        likes_count: 210000,
        views_count: 1820000,
        comments_count: 6890,
        published_at: '2026-09-04T12:00:00Z',
      },
      {
        id: 'ep_qj_2',
        series_id: 'story_queen_of_jozi',
        episode_number: 2,
        title: 'Midnight in Rosebank',
        synopsis: 'A tense standoff at the penthouse reveals an undercover mole inside the private security team.',
        duration_seconds: 79,
        video_url: '/videos/ocean_waves.mp4',
        thumbnail_url: '/posters/queen_of_jozi.jpg',
        is_free: true,
        coin_price: 0,
        cliffhanger_time: 69,
        cliffhanger_hook: 'The security feed was hacked from inside the room.',
        likes_count: 178000,
        views_count: 1450000,
        comments_count: 4920,
        published_at: '2026-09-05T12:00:00Z',
      },
    ],
  },
  {
    id: 'story_ceo_wife',
    title: "The CEO's Secret Wife",
    tagline: 'A fake marriage. A hidden identity. A love that could ruin everything.',
    synopsis: "To save her family's heritage estate from foreclosure, Zandile agrees to a 1-year secret contract marriage with Sandile Ndlovu, Johannesburg's most feared billionaire CEO. But behind closed doors in his Clifton penthouse, cold business turns into undeniable, forbidden passion.",
    cover_image: '/banners/ceo_secret_wife_banner.jpg',
    vertical_poster: '/posters/ceo_secret_wife.jpg',
    genre: 'Romance • 60 Episodes • 16+',
    language: 'English / isiZulu',
    available_languages: ['English', 'isiZulu', 'Swahili', 'French', 'Pidgin'],
    tags: ['#SecretWife', '#BillionaireRomance', '#ContractMarriage', '#SandtonLove', '#Trending'],
    creator_id: 'creator_amaka',
    creator_name: 'Amaka Okafor',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    is_verified_creator: true,
    rating: 4.96,
    total_episodes: 60,
    free_episodes_count: 3,
    coin_price_per_episode: 5,
    total_views: 4920000,
    total_likes: 680000,
    is_original: true,
    is_trending: true,
    status: 'published',
    episodes: [
      {
        id: 'ep_ceo_1',
        series_id: 'story_ceo_wife',
        episode_number: 1,
        title: 'The Proposal',
        synopsis: 'Sandile presents an offer Zandile cannot refuse: 50 million Rand and a ring, with strictly no feelings attached.',
        duration_seconds: 62,
        video_url: '/videos/welele_placeholder.mp4',
        thumbnail_url: '/posters/ceo_secret_wife.jpg',
        is_free: true,
        coin_price: 0,
        cliffhanger_time: 54,
        cliffhanger_hook: 'Sign before the clock strikes midnight.',
        likes_count: 182000,
        views_count: 1640000,
        comments_count: 5420,
        published_at: '2026-08-10T12:00:00Z',
      },
      {
        id: 'ep_ceo_2',
        series_id: 'story_ceo_wife',
        episode_number: 2,
        title: 'The Contract',
        synopsis: 'Clause 7: You must act as the devoted wife in front of the board and media at all costs.',
        duration_seconds: 60,
        video_url: '/videos/ocean_waves.mp4',
        thumbnail_url: '/posters/ceo_secret_wife.jpg',
        is_free: true,
        coin_price: 0,
        cliffhanger_time: 52,
        cliffhanger_hook: 'Who leaked our marriage certificate to the press?',
        likes_count: 154000,
        views_count: 1380000,
        comments_count: 4120,
        published_at: '2026-08-11T12:00:00Z',
      },
    ],
  },
  {
    id: 'story_umembeso',
    title: 'Umembeso: Royal Secrets',
    tagline: 'A traditional royal wedding where every gift carries a deadly secret.',
    synopsis: 'During the opulent royal dowry ceremony in KwaZulu-Natal, an ancient family talisman is stolen, threatening to expose a thirty-year bloodline deception before the vows are sealed.',
    cover_image: '/banners/umembeso_banner.jpg',
    vertical_poster: '/posters/umembeso.jpg',
    genre: 'Romance • Royal • Mystery',
    language: 'isiZulu / isiXhosa',
    available_languages: ['isiZulu', 'isiXhosa', 'English', 'Afrikaans'],
    tags: ['#Umembeso', '#RoyalSecrets', '#ZuluTradition', '#MzansiRomance'],
    creator_id: 'creator_zola',
    creator_name: 'Zola Dlamini',
    creator_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    is_verified_creator: true,
    rating: 4.94,
    total_episodes: 50,
    free_episodes_count: 3,
    coin_price_per_episode: 5,
    total_views: 3410000,
    total_likes: 460000,
    is_original: true,
    is_trending: true,
    status: 'published',
    episodes: [
      {
        id: 'ep_um_1',
        series_id: 'story_umembeso',
        episode_number: 1,
        title: 'The Stolen Talisman',
        synopsis: 'The royal elders open the sacred chest to discover the ancestral spearhead has been replaced with a warning note.',
        duration_seconds: 78,
        video_url: '/videos/flower_bloom.mp4',
        thumbnail_url: '/posters/umembeso.jpg',
        is_free: true,
        coin_price: 0,
        cliffhanger_time: 68,
        cliffhanger_hook: "The note is written in the King's own handwriting.",
        likes_count: 124000,
        views_count: 990000,
        comments_count: 3810,
        published_at: '2026-09-06T12:00:00Z',
      },
    ],
  },
  {
    id: 'story_lagos_confidential',
    title: 'Lagos Confidential',
    tagline: 'High-tech corporate espionage across Victoria Island.',
    synopsis: "A brilliant forensic hacker uncovers a multi-billion naira offshore conduit on the eve of West Africa's biggest telecom merger. With assassins on his trail, 60 seconds is all he has to leak the truth.",
    cover_image: '/banners/lagos_confidential_banner.jpg',
    vertical_poster: '/posters/lagos_confidential.jpg',
    genre: 'Action • Tech • Thriller',
    language: 'English / Pidgin / Yoruba',
    available_languages: ['English', 'Pidgin', 'Yoruba', 'French'],
    tags: ['#LagosConfidential', '#NaijaTech', '#VictoriaIsland', '#CyberThriller'],
    creator_id: 'creator_amaka',
    creator_name: 'Amaka Okafor',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    is_verified_creator: true,
    rating: 4.96,
    total_episodes: 42,
    free_episodes_count: 3,
    coin_price_per_episode: 5,
    total_views: 3720000,
    total_likes: 530000,
    is_original: true,
    is_trending: true,
    status: 'published',
    episodes: [
      {
        id: 'ep_lc_1',
        series_id: 'story_lagos_confidential',
        episode_number: 1,
        title: 'The Decryption Key',
        synopsis: 'A rooftop server room in Ikoyi is breached 15 minutes before the boardroom press conference.',
        duration_seconds: 82,
        video_url: '/videos/welele_placeholder.mp4',
        thumbnail_url: '/posters/lagos_confidential.jpg',
        is_free: true,
        coin_price: 0,
        cliffhanger_time: 72,
        cliffhanger_hook: 'The server just self-destructed and transmitted the coordinates.',
        likes_count: 149000,
        views_count: 1180000,
        comments_count: 4200,
        published_at: '2026-09-07T12:00:00Z',
      },
    ],
  },
  {
    id: 'story_zulu_love',
    title: 'Zulu Love Story',
    tagline: 'Two worlds. One unforgettable royal heartbeat.',
    synopsis: 'Prince Sipho of the KwaZulu royal line meets Nandi, an edgy streetwear designer from Braamfontein. When ancestral duty calls him home to an arranged marriage, will he choose the crown or true love?',
    cover_image: '/posters/zulu_love_story.jpg',
    vertical_poster: '/posters/zulu_love_story.jpg',
    genre: 'Romance • Mzansi Originals',
    language: 'isiZulu / English',
    available_languages: ['isiZulu', 'isiXhosa', 'English', 'Afrikaans'],
    tags: ['#ZuluLove', '#RoyalRomance', '#DurbanToJozi', '#MzansiMagic'],
    creator_id: 'creator_zola',
    creator_name: 'Zola Dlamini',
    creator_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    is_verified_creator: true,
    rating: 4.97,
    total_episodes: 45,
    free_episodes_count: 3,
    coin_price_per_episode: 5,
    total_views: 2980000,
    total_likes: 420000,
    is_original: true,
    is_trending: true,
    status: 'published',
    episodes: [
      {
        id: 'ep_zl_1',
        series_id: 'story_zulu_love',
        episode_number: 1,
        title: 'Eyes in Braamfontein',
        synopsis: 'A pop-up fashion show in Johannesburg brings two completely different souls face to face.',
        duration_seconds: 74,
        video_url: '/videos/welele_placeholder.mp4',
        thumbnail_url: '/posters/zulu_love_story.jpg',
        is_free: true,
        coin_price: 0,
        cliffhanger_time: 64,
        cliffhanger_hook: "He didn't mention he was a prince.",
        likes_count: 92000,
        views_count: 780000,
        comments_count: 2910,
        published_at: '2026-08-25T12:00:00Z',
      },
    ],
  },
  {
    id: 'story_broken_vows',
    title: 'Broken Vows',
    tagline: 'Every secret comes with a price in high society.',
    synopsis: 'During an ultra-glamorous 10th-anniversary ball in Sandton, an anonymous caller plays a secret recording that exposes betrayal, money laundering, and an unspoken pact from 2014.',
    cover_image: '/posters/broken_vows.jpg',
    vertical_poster: '/posters/broken_vows.jpg',
    genre: 'Drama • Mystery • Thriller',
    language: 'English / isiXhosa',
    available_languages: ['English', 'isiXhosa', 'isiZulu', 'Afrikaans'],
    tags: ['#BrokenVows', '#SandtonScandal', '#Betrayal', '#Cliffhanger'],
    creator_id: 'creator_zola',
    creator_name: 'Zola Dlamini',
    creator_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    is_verified_creator: true,
    rating: 4.92,
    total_episodes: 38,
    free_episodes_count: 3,
    coin_price_per_episode: 5,
    total_views: 2450000,
    total_likes: 380000,
    is_original: true,
    is_trending: true,
    status: 'published',
    episodes: [
      {
        id: 'ep_bv_1',
        series_id: 'story_broken_vows',
        episode_number: 1,
        title: 'The Anniversary Toast',
        synopsis: 'A crystal champagne glass shatters as the projector reveals evidence no one was meant to see.',
        duration_seconds: 76,
        video_url: '/videos/ocean_waves.mp4',
        thumbnail_url: '/posters/broken_vows.jpg',
        is_free: true,
        coin_price: 0,
        cliffhanger_time: 66,
        cliffhanger_hook: 'Who switched the USB drive at the podium?',
        likes_count: 87000,
        views_count: 710000,
        comments_count: 2180,
        published_at: '2026-08-28T12:00:00Z',
      },
    ],
  },
  {
    id: 'story_the_hustlers',
    title: 'The Hustlers',
    tagline: 'From Soweto streets to Sandton skyscrapers.',
    synopsis: "Three ambitious street hustlers from Soweto execute a daring high-tech takeover of Johannesburg's biggest private gold bullion syndicate.",
    cover_image: '/posters/the_hustlers.jpg',
    vertical_poster: '/posters/the_hustlers.jpg',
    genre: 'Crime • Action • Thriller',
    language: 'isiZulu / Tsotsitaal / English',
    available_languages: ['isiZulu', 'English', 'Sesotho', 'Afrikaans'],
    tags: ['#TheHustlers', '#JoziUnderground', '#Action', '#SowetoToSandton'],
    creator_id: 'creator_kofi',
    creator_name: 'Kofi Mensah',
    creator_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    is_verified_creator: true,
    rating: 4.95,
    total_episodes: 40,
    free_episodes_count: 3,
    coin_price_per_episode: 5,
    total_views: 3120000,
    total_likes: 480000,
    is_original: true,
    is_trending: true,
    status: 'published',
    episodes: [
      {
        id: 'ep_th_1',
        series_id: 'story_the_hustlers',
        episode_number: 1,
        title: 'The Gold Blueprint',
        synopsis: 'A secret meeting in Maboneng uncovers the security codes to the Carlton Centre underground vault.',
        duration_seconds: 80,
        video_url: '/videos/flower_bloom.mp4',
        thumbnail_url: '/posters/the_hustlers.jpg',
        is_free: true,
        coin_price: 0,
        cliffhanger_time: 70,
        cliffhanger_hook: 'The alarm just triggered 3 minutes early.',
        likes_count: 104000,
        views_count: 890000,
        comments_count: 3100,
        published_at: '2026-08-30T12:00:00Z',
      },
    ],
  },
  {
    id: 'story_campus_royals',
    title: 'Campus Royals',
    tagline: 'Privilege, power, and secret society scandals.',
    synopsis: 'At an elite Cape Town university, the secret student council decides who rises and who falls. A fearless scholarship student vows to tear down the dynasty from within.',
    cover_image: '/posters/campus_royals.jpg',
    vertical_poster: '/posters/campus_royals.jpg',
    genre: 'Drama • Youth • Ambition',
    language: 'English / isiXhosa',
    available_languages: ['English', 'isiXhosa', 'Afrikaans'],
    tags: ['#CampusRoyals', '#UCTDynasty', '#SecretSociety', '#Drama'],
    creator_id: 'creator_wanjiku',
    creator_name: 'Wanjiku Mwangi',
    creator_avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=400&q=80',
    is_verified_creator: true,
    rating: 4.88,
    total_episodes: 40,
    free_episodes_count: 3,
    coin_price_per_episode: 5,
    total_views: 1980000,
    total_likes: 310000,
    is_original: true,
    is_trending: true,
    status: 'published',
    episodes: [
      {
        id: 'ep_cr_1',
        series_id: 'story_campus_royals',
        episode_number: 1,
        title: 'The Induction',
        synopsis: 'The midnight bell rings at Jameson Hall as the masked council initiates the chosen few.',
        duration_seconds: 75,
        video_url: '/videos/sample_drama.mp4',
        thumbnail_url: '/posters/campus_royals.jpg',
        is_free: true,
        coin_price: 0,
        cliffhanger_time: 65,
        cliffhanger_hook: 'She refused to take the loyalty oath.',
        likes_count: 78000,
        views_count: 640000,
        comments_count: 1820,
        published_at: '2026-09-01T12:00:00Z',
      },
    ],
  },
  {
    id: 'story_barrio_billionaire',
    title: 'Barrio Billionaire',
    tagline: 'Built from nothing. Feared by everyone.',
    synopsis: "From a tiny spaza shop in Soweto to commanding Africa's most valuable fintech empire, Thabo faces old-money families trying to take his company down.",
    cover_image: '/posters/barrio_billionaire.jpg',
    vertical_poster: '/posters/barrio_billionaire.jpg',
    genre: 'Drama • Dynasty • Tech',
    language: 'isiZulu / English',
    available_languages: ['isiZulu', 'English', 'Sesotho'],
    tags: ['#BarrioBillionaire', '#FintechHustle', '#JoziPower', '#Dynasty'],
    creator_id: 'creator_zola',
    creator_name: 'Zola Dlamini',
    creator_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    is_verified_creator: true,
    rating: 4.94,
    total_episodes: 48,
    free_episodes_count: 3,
    coin_price_per_episode: 5,
    total_views: 2750000,
    total_likes: 390000,
    is_original: true,
    is_trending: true,
    status: 'published',
    episodes: [
      {
        id: 'ep_bb_1',
        series_id: 'story_barrio_billionaire',
        episode_number: 1,
        title: 'The Hostile Takeover',
        synopsis: "Sandton investment bankers laugh at Thabo's valuation—until his app clears 10 million transactions overnight.",
        duration_seconds: 78,
        video_url: '/videos/welele_placeholder.mp4',
        thumbnail_url: '/posters/barrio_billionaire.jpg',
        is_free: true,
        coin_price: 0,
        cliffhanger_time: 68,
        cliffhanger_hook: 'We own 51% of your bank as of 9 AM.',
        likes_count: 91000,
        views_count: 790000,
        comments_count: 2740,
        published_at: '2026-09-02T12:00:00Z',
      },
    ],
  },
  {
    id: 'story_heist_game',
    title: 'Heist Game',
    tagline: 'One night. Zero room for error.',
    synopsis: "An elite crew of cybersecurity prodigies and street specialists plan an impossible raid on a subterranean Cape Town vault during the New Year's Eve gala.",
    cover_image: '/posters/heist_game.jpg',
    vertical_poster: '/posters/heist_game.jpg',
    genre: 'Crime • Action • Thriller',
    language: 'English / Afrikaans',
    available_languages: ['English', 'Afrikaans', 'isiXhosa'],
    tags: ['#HeistGame', '#CapeTownAction', '#HighStakes', '#Thriller'],
    creator_id: 'creator_kofi',
    creator_name: 'Kofi Mensah',
    creator_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    is_verified_creator: true,
    rating: 4.91,
    total_episodes: 40,
    free_episodes_count: 3,
    coin_price_per_episode: 5,
    total_views: 2180000,
    total_likes: 340000,
    is_original: true,
    is_trending: true,
    status: 'published',
    episodes: [
      {
        id: 'ep_hg_1',
        series_id: 'story_heist_game',
        episode_number: 1,
        title: 'The Countdown Begins',
        synopsis: 'The laser grid trips in the penthouse, giving the crew exactly 60 seconds to bypass the biometric vault.',
        duration_seconds: 80,
        video_url: '/videos/ocean_waves.mp4',
        thumbnail_url: '/posters/heist_game.jpg',
        is_free: true,
        coin_price: 0,
        cliffhanger_time: 70,
        cliffhanger_hook: "The lasers didn't shut down.",
        likes_count: 84000,
        views_count: 720000,
        comments_count: 2100,
        published_at: '2026-09-03T12:00:00Z',
      },
    ],
  },
  {
    id: 'story_sandton_nights',
    title: 'Sandton Nights',
    tagline: 'High stakes, high society, and dangerous promises under the Jozi skyline.',
    synopsis: 'An undercover forensic investigator infiltrates an exclusive VIP poker circuit in Sandton to expose how offshore billions are moved behind crystal chandeliers.',
    cover_image: '/banners/queen_of_jozi_banner.jpg',
    vertical_poster: '/posters/queen_of_jozi.jpg',
    genre: 'Drama • Mystery • Glamour',
    language: 'English / isiZulu',
    available_languages: ['English', 'isiZulu', 'isiXhosa', 'Afrikaans'],
    tags: ['#SandtonNights', '#JoziGlamour', '#HighStakes', '#MzansiOriginal'],
    creator_id: 'creator_zola',
    creator_name: 'Zola Dlamini',
    creator_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    is_verified_creator: true,
    rating: 4.93,
    total_episodes: 36,
    free_episodes_count: 3,
    coin_price_per_episode: 5,
    total_views: 2650000,
    total_likes: 395000,
    is_original: true,
    is_trending: true,
    status: 'published',
    episodes: [
      {
        id: 'ep_sn_1',
        series_id: 'story_sandton_nights',
        episode_number: 1,
        title: 'The Platinum Chip',
        synopsis: 'A single hand of high-stakes poker reveals who is secretly controlling the mining concessions.',
        duration_seconds: 76,
        video_url: '/videos/flower_bloom.mp4',
        thumbnail_url: '/posters/queen_of_jozi.jpg',
        is_free: true,
        coin_price: 0,
        cliffhanger_time: 67,
        cliffhanger_hook: 'Every chip at the table has an RFID tracer.',
        likes_count: 98000,
        views_count: 810000,
        comments_count: 2450,
        published_at: '2026-09-05T12:00:00Z',
      },
    ],
  },
  {
    id: 'story_durban_heat',
    title: 'Durban Heat',
    tagline: 'Under the golden sun, the street race for justice begins.',
    synopsis: "Two estranged brothers on opposite sides of the law collide when Durban's underground shipping lanes become the battleground for a missing shipment of uncut gemstones.",
    cover_image: '/banners/lagos_confidential_banner.jpg',
    vertical_poster: '/posters/the_hustlers.jpg',
    genre: 'Action • Crime • Fast Pace',
    language: 'isiZulu / English',
    available_languages: ['isiZulu', 'English', 'Afrikaans'],
    tags: ['#DurbanHeat', '#ActionThriller', '#CoastalCrime', '#WeleleOriginal'],
    creator_id: 'creator_kofi',
    creator_name: 'Kofi Mensah',
    creator_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    is_verified_creator: true,
    rating: 4.89,
    total_episodes: 44,
    free_episodes_count: 3,
    coin_price_per_episode: 5,
    total_views: 2430000,
    total_likes: 360000,
    is_original: true,
    is_trending: true,
    status: 'published',
    episodes: [
      {
        id: 'ep_dh_1',
        series_id: 'story_durban_heat',
        episode_number: 1,
        title: 'Harbor Gridlock',
        synopsis: 'A high-speed pursuit through the Durban harbor terminals traps the team in container sector 4.',
        duration_seconds: 82,
        video_url: '/videos/welele_placeholder.mp4',
        thumbnail_url: '/posters/the_hustlers.jpg',
        is_free: true,
        coin_price: 0,
        cliffhanger_time: 73,
        cliffhanger_hook: 'The crane controls were bypassed remotely.',
        likes_count: 91000,
        views_count: 750000,
        comments_count: 2190,
        published_at: '2026-09-06T12:00:00Z',
      },
    ],
  },
  {
    id: 'story_the_spaza_king',
    title: 'The Spaza King',
    tagline: 'From a corner container in Soweto to a township retail empire.',
    synopsis: 'Armed with grit, humor, and an unstoppable delivery drone experiment, Bongani revolutionizes township commerce while outsmarting loan sharks and corporate retail giants.',
    cover_image: '/banners/umembeso_banner.jpg',
    vertical_poster: '/posters/barrio_billionaire.jpg',
    genre: 'Comedy • Township • Hustle',
    language: 'isiZulu / Tsotsitaal / English',
    available_languages: ['isiZulu', 'English', 'Sesotho', 'isiXhosa'],
    tags: ['#TheSpazaKing', '#TownshipHustle', '#MzansiComedy', '#Heartwarming'],
    creator_id: 'creator_wanjiku',
    creator_name: 'Wanjiku Mwangi',
    creator_avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=400&q=80',
    is_verified_creator: true,
    rating: 4.95,
    total_episodes: 32,
    free_episodes_count: 3,
    coin_price_per_episode: 5,
    total_views: 3290000,
    total_likes: 490000,
    is_original: true,
    is_trending: true,
    status: 'published',
    episodes: [
      {
        id: 'ep_sk_1',
        series_id: 'story_the_spaza_king',
        episode_number: 1,
        title: 'The 3-Minute Delivery',
        synopsis: "Bongani launches Soweto's fastest bunny chow delivery on an electric scooter, catching the eye of a Sandton venture capitalist.",
        duration_seconds: 70,
        video_url: '/videos/sample_drama.mp4',
        thumbnail_url: '/posters/barrio_billionaire.jpg',
        is_free: true,
        coin_price: 0,
        cliffhanger_time: 60,
        cliffhanger_hook: 'The investor just offered 5 million on the spot.',
        likes_count: 115000,
        views_count: 980000,
        comments_count: 3410,
        published_at: '2026-09-07T12:00:00Z',
      },
    ],
  },
];
